image: node

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/    


pages:
  cache:
    paths:
    - node-modules/
  before_script:
    - npm ci --cache .npm
  script:
    - npm run gitlab
  artifacts:
    paths:
      - public