name: Publish on GitHub pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚚
        uses: actions/checkout@v4.1.1
      - name: Build and Deploy 🚀
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/galarzaa
