name: Publish on GitHub pages
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Builds and deploys Angular page
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@@1.3.2
      with:
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/galarzaa